In [127]:
!pip install -U sklearn
!pip install -U lightautoml
!pip install joblib


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [128]:
# Standard python libraries
import os
import time
import requests

# Essential DS libraries
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import torch

# LightAutoML presets, task and report generation
from lightautoml.automl.presets.tabular_presets import TabularAutoML
from lightautoml.automl.presets.tabular_presets import TabularUtilizedAutoML
from lightautoml.tasks import Task

import joblib

In [129]:
TARGET_NAME = 'Кол-во запросов в месяц'
data = pd.read_csv('touristObjects3.csv')
data

Название точки привлечения туристов  \
0      Архангельский театр драмы имени М.В. Ломоносова   
1    "Беломорские узоры" (Народные художественные п...   
2                       Архангельский молодежный театр   
3         Архангельский музей изобразительных искусств   
4                            Архангельский театр кукол   
..                                                 ...   
102        Историко-мемориальный музей М.В. Ломоносова   
103                                    Село Ломоносово   
104               Фабрика Холмогорской резьбы по кости   
105         Церковь Димитрия Солунского, с. Ломоносово   
106            Шенкурский районный краеведческий музей   

     Кол-во запросов в месяц Тип точки привлечения туристов    Долгота  \
0                     9000.0                          Театр  40.515280   
1                      466.0               Этнический центр  40.520756   
2                      446.0                          Театр  40.519231   
3                      248.0                          Музей  40.518417   
4                     1400.0                          Театр  40.529639   
..                       ...                            ...        ...   
102                    126.0          Достопримечательность  41.733645   
103                   4073.0          Достопримечательность  41.732359   
104                     37.0               Этнический центр  41.733516   
105                     38.0          Достопримечательность  41.739181   
106                    150.0          Достопримечательность  42.902558   

     Доступность автомобиля  Доступность автобуса  Доступность внедорожника  \
0                     False                 False                     False   
1                      True                  True                     False   
2                      True                  True                     False   
3                      True                  True                     False   
4                      True                  True                     False   
..                      ...                   ...                       ...   
102                    True                  True                     False   
103                    True                  True                     False   
104                    True                  True                     False   
105                    True                  True                     False   
106                    True                  True                     False   

     Доступность водныого транспорта  Доступность самолета     Широта  ...  \
0                              False                 False  64.536504  ...   
1                              False                 False  64.559452  ...   
2                              False                 False  64.549876  ...   
3                              False                 False  64.539888  ...   
4                              False                 False  64.531850  ...   
..                               ...                   ...        ...  ...   
102                            False                 False  64.230200  ...   
103                            False                 False  64.229380  ...   
104                            False                 False  64.230262  ...   
105                            False                 False  64.231620  ...   
106                            False                 False  62.103525  ...   

     Детский туризм  Городские достопримечательности  Достопримечательность  \
0             False                            False                  False   
1             False                            False                  False   
2             False                            False                  False   
3             False                            False                  False   
4             False                            False                  False   
..              ...                              ...                    .

In [130]:
#костыль
data = data.drop(columns=['Тип точки привлечения туристов'])
data

Название точки привлечения туристов  \
0      Архангельский театр драмы имени М.В. Ломоносова   
1    "Беломорские узоры" (Народные художественные п...   
2                       Архангельский молодежный театр   
3         Архангельский музей изобразительных искусств   
4                            Архангельский театр кукол   
..                                                 ...   
102        Историко-мемориальный музей М.В. Ломоносова   
103                                    Село Ломоносово   
104               Фабрика Холмогорской резьбы по кости   
105         Церковь Димитрия Солунского, с. Ломоносово   
106            Шенкурский районный краеведческий музей   

     Кол-во запросов в месяц    Долгота  Доступность автомобиля  \
0                     9000.0  40.515280                   False   
1                      466.0  40.520756                    True   
2                      446.0  40.519231                    True   
3                      248.0  40.518417                    True   
4                     1400.0  40.529639                    True   
..                       ...        ...                     ...   
102                    126.0  41.733645                    True   
103                   4073.0  41.732359                    True   
104                     37.0  41.733516                    True   
105                     38.0  41.739181                    True   
106                    150.0  42.902558                    True   

     Доступность автобуса  Доступность внедорожника  \
0                   False                     False   
1                    True                     False   
2                    True                     False   
3                    True                     False   
4                    True                     False   
..                    ...                       ...   
102                  True                     False   
103                  True                     False   
104                  True                     False   
105                  True                     False   
106                  True                     False   

     Доступность водныого транспорта  Доступность самолета     Широта  Театр  \
0                              False                 False  64.536504   True   
1                              False                 False  64.559452  False   
2                              False                 False  64.549876   True   
3                              False                 False  64.539888  False   
4                              False                 False  64.531850   True   
..                               ...                   ...        ...    ...   
102                            False                 False  64.230200  False   
103                            False                 False  64.229380  False   
104                            False                 False  64.230262  False   
105                            False                 False  64.231620  False   
106                            False                 False  62.103525  False   

     ...  Детский туризм  Городские достопримечательности  \
0    ...           False                            False   
1    ...           False                            False   
2    ...           False                            False   
3    ...           False                            False   
4    ...           False                            False   
..   ...             ...                              ...   
102  ...           False                            False   
103  ...           False                            False   
104  ...           False                            False   
105  ...           False                            False   
106  ...           False                            False   

     Достопримечательность  Культурный центр  Судостроение  Нац. парк  \
0                    False             False         False      False   
1               

In [131]:
data['Кол-во запросов в месяц'].mean()

684.2242990654206

In [132]:
Y = data.iloc[:]['Кол-во запросов в месяц']
X = data.drop(columns=['Название точки привлечения туристов', 'Кол-во запросов в месяц'])
data

Название точки привлечения туристов  \
0      Архангельский театр драмы имени М.В. Ломоносова   
1    "Беломорские узоры" (Народные художественные п...   
2                       Архангельский молодежный театр   
3         Архангельский музей изобразительных искусств   
4                            Архангельский театр кукол   
..                                                 ...   
102        Историко-мемориальный музей М.В. Ломоносова   
103                                    Село Ломоносово   
104               Фабрика Холмогорской резьбы по кости   
105         Церковь Димитрия Солунского, с. Ломоносово   
106            Шенкурский районный краеведческий музей   

     Кол-во запросов в месяц    Долгота  Доступность автомобиля  \
0                     9000.0  40.515280                   False   
1                      466.0  40.520756                    True   
2                      446.0  40.519231                    True   
3                      248.0  40.518417                    True   
4                     1400.0  40.529639                    True   
..                       ...        ...                     ...   
102                    126.0  41.733645                    True   
103                   4073.0  41.732359                    True   
104                     37.0  41.733516                    True   
105                     38.0  41.739181                    True   
106                    150.0  42.902558                    True   

     Доступность автобуса  Доступность внедорожника  \
0                   False                     False   
1                    True                     False   
2                    True                     False   
3                    True                     False   
4                    True                     False   
..                    ...                       ...   
102                  True                     False   
103                  True                     False   
104                  True                     False   
105                  True                     False   
106                  True                     False   

     Доступность водныого транспорта  Доступность самолета     Широта  Театр  \
0                              False                 False  64.536504   True   
1                              False                 False  64.559452  False   
2                              False                 False  64.549876   True   
3                              False                 False  64.539888  False   
4                              False                 False  64.531850   True   
..                               ...                   ...        ...    ...   
102                            False                 False  64.230200  False   
103                            False                 False  64.229380  False   
104                            False                 False  64.230262  False   
105                            False                 False  64.231620  False   
106                            False                 False  62.103525  False   

     ...  Детский туризм  Городские достопримечательности  \
0    ...           False                            False   
1    ...           False                            False   
2    ...           False                            False   
3    ...           False                            False   
4    ...           False                            False   
..   ...             ...                              ...   
102  ...           False                            False   
103  ...           False                            False   
104  ...           False                            False   
105  ...           False                            False   
106  ...           False                            False   

     Достопримечательность  Культурный центр  Судостроение  Нац. парк  \
0                    False             False         False      False   
1               

In [148]:
data.columns

Index(['Название точки привлечения туристов', 'Кол-во запросов в месяц',
       'Долгота', 'Доступность автомобиля', 'Доступность автобуса',
       'Доступность внедорожника', 'Доступность водныого транспорта',
       'Доступность самолета', 'Широта', 'Театр', 'Этнический центр', 'Музей',
       'Детский туризм', 'Городские достопримечательности',
       'Достопримечательность', 'Культурный центр', 'Судостроение',
       'Нац. парк', 'Санаторий', 'Обзорная площадка', 'Горнолыжный курорт',
       'Коэффициент кол-ва запросов в месяц окружающих объектов'],
      dtype='object')

In [134]:
train, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.15)

In [135]:
train['Кол-во запросов в месяц'] = ytrain
xtest['Кол-во запросов в месяц'] = ytest

In [136]:
task = Task('reg')
roles = {'target': TARGET_NAME}
N_FOLDS = 5
TIMEOUT = 60 * 300  # 30 minutes
automl = TabularAutoML(
    task=task,  # required
    timeout=TIMEOUT,
    cpu_limit=8,
    reader_params={'n_jobs': 8, 'cv': N_FOLDS}
)

In [137]:
tr_data=train
te_data=xtest
oof_preds = automl.fit_predict(tr_data, roles=roles, verbose=1)

[00:50:25] Stdout logging level is INFO.
[00:50:25] Task: reg

[00:50:25] Start automl preset with listed constraints:
[00:50:25] - time: 18000.00 seconds
[00:50:25] - CPU: 8 cores
[00:50:25] - memory: 16 GB

[00:50:25] Train data shape: (90, 21)

[00:50:29] Layer 1 train process start. Time left 17995.30 secs
[00:50:29] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[00:50:30] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -3833329.616877018
[00:50:30] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[00:50:30] Time left 17994.61 secs

[00:50:30] Selector_LightGBM fitting and predicting completed
[00:50:30] Start fitting Lvl_0_Pipe_1_Mod_0_LightGBM ...
[00:50:30] Fitting Lvl_0_Pipe_1_Mod_0_LightGBM finished. score = -4317812.744381277
[00:50:30] Lvl_0_Pipe_1_Mod_0_LightGBM fitting and predicting completed
[00:50:30] Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ... Time budget is 300.00 secs
[00:50:34] Hyperparameters optimization for Lvl_0

In [138]:
print(automl.create_model_str_desc())

Final prediction for new objects (level 0) = 
	 0.94839 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.05161 * (5 averaged models Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM) 


In [139]:
out_of_fold_predictions = automl.fit_predict(tr_data, roles = roles, verbose = 1)
test_predictions = automl.predict(te_data)
test_predictions

[00:50:37] Stdout logging level is INFO.
[00:50:37] Task: reg

[00:50:37] Start automl preset with listed constraints:
[00:50:37] - time: 18000.00 seconds
[00:50:37] - CPU: 8 cores
[00:50:37] - memory: 16 GB

[00:50:37] Train data shape: (90, 21)

[00:50:37] Layer 1 train process start. Time left 17999.91 secs
[00:50:37] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[00:50:38] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -3833329.616877018
[00:50:38] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[00:50:38] Time left 17999.23 secs

[00:50:38] Selector_LightGBM fitting and predicting completed
[00:50:38] Start fitting Lvl_0_Pipe_1_Mod_0_LightGBM ...
[00:50:38] Fitting Lvl_0_Pipe_1_Mod_0_LightGBM finished. score = -4317812.744381277
[00:50:38] Lvl_0_Pipe_1_Mod_0_LightGBM fitting and predicting completed
[00:50:38] Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ... Time budget is 300.00 secs
[00:50:42] Hyperparameters optimization for Lvl_0

array([[ 113.748405],
       [ 478.43637 ],
       [  60.4146  ],
       [ 903.47076 ],
       [ 248.48335 ],
       [ 628.14655 ],
       [ 684.5095  ],
       [1306.1827  ],
       [ 551.3865  ],
       [ 137.95117 ],
       [ 212.37051 ],
       [  41.812428],
       [ 393.28732 ],
       [ 288.11456 ],
       [ 512.6233  ],
       [2881.819   ],
       [ 715.9315  ]], dtype=float32)

In [140]:
from sklearn.metrics import mean_absolute_error
print(f'OOF score: {mean_absolute_error(tr_data[roles["target"]].values, out_of_fold_predictions.data[:, 0])}')
print(f'HOLDOUT score: {mean_absolute_error(te_data[roles["target"]].values, test_predictions.data[:, 0])}')

OOF score: 837.3232215457492
HOLDOUT score: 838.2249594295727


In [144]:
test_predictions.data[:, 0]

array([ 113.748405,  478.43637 ,   60.4146  ,  903.47076 ,  248.48335 ,
        628.14655 ,  684.5095  , 1306.1827  ,  551.3865  ,  137.95117 ,
        212.37051 ,   41.812428,  393.28732 ,  288.11456 ,  512.6233  ,
       2881.819   ,  715.9315  ], dtype=float32)

In [145]:
te_data[roles["target"]].values

array([2.160e+02, 3.700e+01, 1.000e+00, 2.300e+01, 8.500e+01, 3.050e+02,
       1.180e+02, 9.000e+03, 1.079e+03, 1.000e+00, 2.300e+01, 1.000e+00,
       6.700e+01, 1.500e+03, 2.400e+01, 2.462e+03, 3.800e+01])

In [141]:
joblib.dump(automl, 'regression_model.joblib')

['regression_model.joblib']

In [142]:
reg = joblib.load('regression_model.joblib')

In [143]:
predictions = reg.predict(te_data)
predictions

array([[ 113.748405],
       [ 478.43637 ],
       [  60.4146  ],
       [ 903.47076 ],
       [ 248.48335 ],
       [ 628.14655 ],
       [ 684.5095  ],
       [1306.1827  ],
       [ 551.3865  ],
       [ 137.95117 ],
       [ 212.37051 ],
       [  41.812428],
       [ 393.28732 ],
       [ 288.11456 ],
       [ 512.6233  ],
       [2881.819   ],
       [ 715.9315  ]], dtype=float32)